#!/bin/bash
#
# Makes html-pages of all Python scripts in current directory using pydoc
#
# Copyright 2012 Matthias Cuntz - mc (at) macu.de
#
# License
# This file is part of the UFZ Python library.
#
# The UFZ Python library is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The UFZ Python library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with the UFZ makefile project (cf. gpl.txt and lgpl.txt).
# If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2012-2014 Matthias Cuntz
#
set -e
#
#trap cleanup 1 2 3 6
#
prog=$(basename $0)
#dprog=$(dirname $0)
isdir=${PWD}
#pid="$$"
#TMP=${TMPDIR:-"/tmp"}
#
# usage
function usage ()
{
    printf "\n"
    printf "${prog} [-h]\n"
    printf "\n"
    printf "Makes html-pages of all Python scripts in current directory using pydoc.\n"
    printf "Pages will be in directory html. There is a summary page index.html.\n"
    printf "\n"
    printf "Options\n"
    printf "    -h              Prints this help screen.\n"
    printf "\n"
    printf "Examples\n"
    printf "    ${prog}\n"
}
#
# # cleanup
# function cleanup ()
# {
#   \rm -f ${TMP}/*.${pid}*
#   exit 1
# }
#
# switches
while getopts "h" Option ; do
    case ${Option} in
	h) usage 1>&2; exit 0;;
	*) printf "Error ${prog}: unimplemented option.\n";  usage 1>&2; exit 1;;
    esac
done
shift $((${OPTIND} - 1))
#
# Delete old html files
if [[ ! -d "html" ]] ; then mkdir html ; fi
\rm -f html/*
#
# Create header of index html
printf "<HTML>\n" > html/index.html
printf "<HEAD>\n" >> html/index.html
printf "<TITLE> List of PYTHON files</TITLE>\n" >> html/index.html
printf "</HEAD>\n" >> html/index.html
printf "<BODY>\n" >> html/index.html
printf "<strong><font size='+1'>PYTHON files</font></strong><br><br>\n" >> html/index.html
printf "<PRE>\n" >> html/index.html
#
# Create new html files
for i in $(\ls *.py) ; do
    m=${i%.py}
    pydoc -w ${m}
    h=${i/%.py/.html}
    sed -e "s|${isdir}|..|g" ${h} > html/${h}
    \rm ${h}
    printf "&nbsp;&nbsp;<a href=${h}>${i}</a>\n" >> html/index.html
done
#
# Finish index html
printf "</PRE>\n" >> html/index.html
printf "</BODY>\n" >> html/index.html
printf "</HTML>\n" >> html/index.html
#
exit 0
